/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CompanyRouteRouteImport } from './routes/company/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompanyIndexRouteImport } from './routes/company/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as CompanyTripsRouteImport } from './routes/company/trips'
import { Route as CompanyStaffRouteImport } from './routes/company/staff'
import { Route as CompanyRevenueRouteImport } from './routes/company/revenue'
import { Route as CompanyFleetRouteImport } from './routes/company/fleet'
import { Route as CompanyBookingsRouteImport } from './routes/company/bookings'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminRoutesRouteImport } from './routes/admin/routes'
import { Route as AdminRolesRouteImport } from './routes/admin/roles'
import { Route as AdminRevenueRouteImport } from './routes/admin/revenue'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminLocationsRouteImport } from './routes/admin/locations'
import { Route as AdminCompaniesRouteImport } from './routes/admin/companies'
import { Route as AdminBookingsRouteImport } from './routes/admin/bookings'

const CompanyRouteRoute = CompanyRouteRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyIndexRoute = CompanyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CompanyRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const CompanyTripsRoute = CompanyTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => CompanyRouteRoute,
} as any)
const CompanyStaffRoute = CompanyStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => CompanyRouteRoute,
} as any)
const CompanyRevenueRoute = CompanyRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => CompanyRouteRoute,
} as any)
const CompanyFleetRoute = CompanyFleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => CompanyRouteRoute,
} as any)
const CompanyBookingsRoute = CompanyBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => CompanyRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRoutesRoute = AdminRoutesRouteImport.update({
  id: '/routes',
  path: '/routes',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRevenueRoute = AdminRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLocationsRoute = AdminLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCompaniesRoute = AdminCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/company': typeof CompanyRouteRouteWithChildren
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/routes': typeof AdminRoutesRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/login': typeof AuthLoginRoute
  '/company/bookings': typeof CompanyBookingsRoute
  '/company/fleet': typeof CompanyFleetRoute
  '/company/revenue': typeof CompanyRevenueRoute
  '/company/staff': typeof CompanyStaffRoute
  '/company/trips': typeof CompanyTripsRoute
  '/admin/': typeof AdminIndexRoute
  '/company/': typeof CompanyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/routes': typeof AdminRoutesRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/login': typeof AuthLoginRoute
  '/company/bookings': typeof CompanyBookingsRoute
  '/company/fleet': typeof CompanyFleetRoute
  '/company/revenue': typeof CompanyRevenueRoute
  '/company/staff': typeof CompanyStaffRoute
  '/company/trips': typeof CompanyTripsRoute
  '/admin': typeof AdminIndexRoute
  '/company': typeof CompanyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/company': typeof CompanyRouteRouteWithChildren
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/routes': typeof AdminRoutesRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/login': typeof AuthLoginRoute
  '/company/bookings': typeof CompanyBookingsRoute
  '/company/fleet': typeof CompanyFleetRoute
  '/company/revenue': typeof CompanyRevenueRoute
  '/company/staff': typeof CompanyStaffRoute
  '/company/trips': typeof CompanyTripsRoute
  '/admin/': typeof AdminIndexRoute
  '/company/': typeof CompanyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/company'
    | '/admin/bookings'
    | '/admin/companies'
    | '/admin/locations'
    | '/admin/reports'
    | '/admin/revenue'
    | '/admin/roles'
    | '/admin/routes'
    | '/admin/users'
    | '/auth/login'
    | '/company/bookings'
    | '/company/fleet'
    | '/company/revenue'
    | '/company/staff'
    | '/company/trips'
    | '/admin/'
    | '/company/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/bookings'
    | '/admin/companies'
    | '/admin/locations'
    | '/admin/reports'
    | '/admin/revenue'
    | '/admin/roles'
    | '/admin/routes'
    | '/admin/users'
    | '/auth/login'
    | '/company/bookings'
    | '/company/fleet'
    | '/company/revenue'
    | '/company/staff'
    | '/company/trips'
    | '/admin'
    | '/company'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/company'
    | '/admin/bookings'
    | '/admin/companies'
    | '/admin/locations'
    | '/admin/reports'
    | '/admin/revenue'
    | '/admin/roles'
    | '/admin/routes'
    | '/admin/users'
    | '/auth/login'
    | '/company/bookings'
    | '/company/fleet'
    | '/company/revenue'
    | '/company/staff'
    | '/company/trips'
    | '/admin/'
    | '/company/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  CompanyRouteRoute: typeof CompanyRouteRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/': {
      id: '/company/'
      path: '/'
      fullPath: '/company/'
      preLoaderRoute: typeof CompanyIndexRouteImport
      parentRoute: typeof CompanyRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/company/trips': {
      id: '/company/trips'
      path: '/trips'
      fullPath: '/company/trips'
      preLoaderRoute: typeof CompanyTripsRouteImport
      parentRoute: typeof CompanyRouteRoute
    }
    '/company/staff': {
      id: '/company/staff'
      path: '/staff'
      fullPath: '/company/staff'
      preLoaderRoute: typeof CompanyStaffRouteImport
      parentRoute: typeof CompanyRouteRoute
    }
    '/company/revenue': {
      id: '/company/revenue'
      path: '/revenue'
      fullPath: '/company/revenue'
      preLoaderRoute: typeof CompanyRevenueRouteImport
      parentRoute: typeof CompanyRouteRoute
    }
    '/company/fleet': {
      id: '/company/fleet'
      path: '/fleet'
      fullPath: '/company/fleet'
      preLoaderRoute: typeof CompanyFleetRouteImport
      parentRoute: typeof CompanyRouteRoute
    }
    '/company/bookings': {
      id: '/company/bookings'
      path: '/bookings'
      fullPath: '/company/bookings'
      preLoaderRoute: typeof CompanyBookingsRouteImport
      parentRoute: typeof CompanyRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/routes': {
      id: '/admin/routes'
      path: '/routes'
      fullPath: '/admin/routes'
      preLoaderRoute: typeof AdminRoutesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/revenue': {
      id: '/admin/revenue'
      path: '/revenue'
      fullPath: '/admin/revenue'
      preLoaderRoute: typeof AdminRevenueRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/locations': {
      id: '/admin/locations'
      path: '/locations'
      fullPath: '/admin/locations'
      preLoaderRoute: typeof AdminLocationsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/companies': {
      id: '/admin/companies'
      path: '/companies'
      fullPath: '/admin/companies'
      preLoaderRoute: typeof AdminCompaniesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminCompaniesRoute: typeof AdminCompaniesRoute
  AdminLocationsRoute: typeof AdminLocationsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminRevenueRoute: typeof AdminRevenueRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminRoutesRoute: typeof AdminRoutesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminBookingsRoute: AdminBookingsRoute,
  AdminCompaniesRoute: AdminCompaniesRoute,
  AdminLocationsRoute: AdminLocationsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminRevenueRoute: AdminRevenueRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminRoutesRoute: AdminRoutesRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface CompanyRouteRouteChildren {
  CompanyBookingsRoute: typeof CompanyBookingsRoute
  CompanyFleetRoute: typeof CompanyFleetRoute
  CompanyRevenueRoute: typeof CompanyRevenueRoute
  CompanyStaffRoute: typeof CompanyStaffRoute
  CompanyTripsRoute: typeof CompanyTripsRoute
  CompanyIndexRoute: typeof CompanyIndexRoute
}

const CompanyRouteRouteChildren: CompanyRouteRouteChildren = {
  CompanyBookingsRoute: CompanyBookingsRoute,
  CompanyFleetRoute: CompanyFleetRoute,
  CompanyRevenueRoute: CompanyRevenueRoute,
  CompanyStaffRoute: CompanyStaffRoute,
  CompanyTripsRoute: CompanyTripsRoute,
  CompanyIndexRoute: CompanyIndexRoute,
}

const CompanyRouteRouteWithChildren = CompanyRouteRoute._addFileChildren(
  CompanyRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  CompanyRouteRoute: CompanyRouteRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
